[tasks.clean-server]
command = "rm"
args = ["-rf", "server"]

[tasks.clean-client]
command = "rm"
args = ["-rf", "client"]


[tasks.clean]
dependencies = [
    "clean-server",
    "clean-client",
]

[tasks.all]
command = "cargo"
args = ["run"]
dependencies = ["clean"]
