[workspace]
resolver = "2"

members = [
    "memcrab",
    "memcrab-cache",
    "memcrab-server",
    "memcrab-protocol",
]
exclude = ["examples"]

[workspace.dependencies]
anyhow = "1.0.79"
prost = "0.12.3"
tonic = "0.10.2"
tokio = { version = "1.35.1", default-features = false }
