[workspace]
resolver = "2"

members = [
    "memcrab",
    "memcrab-cache",
    "memcrab-protocol",
    "memcrab-cli",
]
exclude = ["examples"]

[workspace.dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
tokio = { version = "1.35.1", default-features = false }
