[workspace]
resolver = "2"

members = [
    "memcrab",
    "memcrab-cache",
    "memcrab-server",
    "memcrab-cli"
]
exclude = ["examples"]

[workspace.dependencies]
prost = "0.12.3"
tonic = "0.10.2"
