[package]
name = "memcrab-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
num_enum = "0.7.2"
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
